/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Models.Weather;
import java.io.IOException;
import javax.swing.Timer;

/**
 *
 * @author Markus
 */
public class WeatherFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WeatherFrame.class.getName());
    private Weather weather = new Weather();
    private Timer updateTimer;
    private int type;

    public static enum TemperatureUnit {
        Celcius,
        Fahrenheit,
        Kelvin
    }

    /**
     * Creates new form NewJFrame
     */
    public WeatherFrame() throws IOException {
        initComponents();
        update();

        updateTimer = new Timer(3600000, (e) -> {
            try {
                update();
            } catch (IOException ex) {
                System.getLogger(WeatherFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
        updateTimer.start();
    }

    public void update() throws IOException {
        weather.update();
        drawPanel1.setWeather(weather);
        graphJPanel1.setWeather(weather);
        currentWeatherJPanel1.setWeather(weather);
        drawPanel1.repaint();
        graphJPanel1.repaint();
        currentWeatherJPanel1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        drawPanel1 = new GUI.DrawPanel();
        graphJPanel1 = new GUI.GraphJPanel();
        currentWeatherJPanel1 = new GUI.CurrentWeatherJPanel();
        celciusRadioButton = new javax.swing.JRadioButton();
        fahrenheitRadioButton = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout drawPanel1Layout = new javax.swing.GroupLayout(drawPanel1);
        drawPanel1.setLayout(drawPanel1Layout);
        drawPanel1Layout.setHorizontalGroup(
            drawPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        drawPanel1Layout.setVerticalGroup(
            drawPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        graphJPanel1.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout graphJPanel1Layout = new javax.swing.GroupLayout(graphJPanel1);
        graphJPanel1.setLayout(graphJPanel1Layout);
        graphJPanel1Layout.setHorizontalGroup(
            graphJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        graphJPanel1Layout.setVerticalGroup(
            graphJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        currentWeatherJPanel1.setBackground(new java.awt.Color(0, 204, 204));

        buttonGroup1.add(celciusRadioButton);
        celciusRadioButton.setSelected(true);
        celciusRadioButton.setText("Celcius(°C)");
        celciusRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celciusRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(fahrenheitRadioButton);
        fahrenheitRadioButton.setText("Fahrenheit(°F)");
        fahrenheitRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fahrenheitRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Kelvin(°K)");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout currentWeatherJPanel1Layout = new javax.swing.GroupLayout(currentWeatherJPanel1);
        currentWeatherJPanel1.setLayout(currentWeatherJPanel1Layout);
        currentWeatherJPanel1Layout.setHorizontalGroup(
            currentWeatherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, currentWeatherJPanel1Layout.createSequentialGroup()
                .addContainerGap(742, Short.MAX_VALUE)
                .addComponent(celciusRadioButton)
                .addGap(18, 18, 18)
                .addComponent(fahrenheitRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        currentWeatherJPanel1Layout.setVerticalGroup(
            currentWeatherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentWeatherJPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(currentWeatherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celciusRadioButton)
                    .addComponent(fahrenheitRadioButton)
                    .addComponent(jRadioButton3))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(drawPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(graphJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(currentWeatherJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(currentWeatherJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drawPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(graphJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void celciusRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celciusRadioButtonActionPerformed
        weather.setMode(TemperatureUnit.Celcius);
        drawPanel1.repaint();
        graphJPanel1.repaint();
        currentWeatherJPanel1.repaint();
    }//GEN-LAST:event_celciusRadioButtonActionPerformed

    private void fahrenheitRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fahrenheitRadioButtonActionPerformed
        weather.setMode(TemperatureUnit.Celcius);
        drawPanel1.repaint();
        graphJPanel1.repaint();
        currentWeatherJPanel1.repaint();
    }//GEN-LAST:event_fahrenheitRadioButtonActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        weather.setMode(TemperatureUnit.Celcius);
        drawPanel1.repaint();
        graphJPanel1.repaint();
        currentWeatherJPanel1.repaint();
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new WeatherFrame().setVisible(true);
            } catch (IOException ex) {
                System.getLogger(WeatherFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton celciusRadioButton;
    private GUI.CurrentWeatherJPanel currentWeatherJPanel1;
    private GUI.DrawPanel drawPanel1;
    private javax.swing.JRadioButton fahrenheitRadioButton;
    private GUI.GraphJPanel graphJPanel1;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
