/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Models.Weather;
import java.io.IOException;
import javax.swing.Timer;

/**
 *
 * @author Markus
 */
public class WheatherFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WheatherFrame.class.getName());
    private Weather weather = new Weather();
    private Timer updateTimer;
    private int type;

    public static enum TemperatureUnit {
        Celcius,
        Fahrenheit,
        Kelvin
    }

    /**
     * Creates new form MainFrame
     */
    public WheatherFrame() throws IOException {
        initComponents();
        update();

        updateTimer = new Timer(3600000, (e) -> {
            try {
                update();
            } catch (IOException ex) {
                System.getLogger(WheatherFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
        updateTimer.start();

    }

    public void update() throws IOException {
        weather.update();
        drawPanel1.setWeather(weather);
        //temperatureLabel.setText(String.valueOf(weather.getCurrentTemperature()));
        //degreesLabel.setText("°C");
        drawPanel1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        temperatureGroup = new javax.swing.ButtonGroup();
        drawPanel1 = new GUI.DrawPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        drawPanel1.setMaximumSize(new java.awt.Dimension(100, 100));
        drawPanel1.setMinimumSize(new java.awt.Dimension(1, 1));

        javax.swing.GroupLayout drawPanel1Layout = new javax.swing.GroupLayout(drawPanel1);
        drawPanel1.setLayout(drawPanel1Layout);
        drawPanel1Layout.setHorizontalGroup(
            drawPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1232, Short.MAX_VALUE)
        );
        drawPanel1Layout.setVerticalGroup(
            drawPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );

        getContentPane().add(drawPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new WheatherFrame().setVisible(true);
            } catch (IOException ex) {
                System.getLogger(WheatherFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.DrawPanel drawPanel1;
    private javax.swing.ButtonGroup temperatureGroup;
    // End of variables declaration//GEN-END:variables
}
